blank_issues_enabled: true
contact_links:
  - name: KC Discord
    url: https://discord.gg/RtSadWM
    about: You can contact me (Tibo#4309) or ask others in the reddit KC discord for support.
  - name: Support discord
    url: https://discord.gg/J7nBD6U
    about: You can also contact me (Tibo#4309) in my own discord server for support.
